var myElement = document.querySelector("#elzero");
console.log(myElement);
var myElement = document.querySelector(".element");
console.log(myElement);
var myElement = document.querySelector("div");
console.log(myElement);
var myElement = document.querySelector("[name='js']");
console.log(myElement);
var myElement = document.querySelectorAll("[name='js']");
console.log(myElement);
var myElement = document.querySelectorAll(".element");
console.log(myElement);
var myElement = document.querySelectorAll("#elzero");
console.log(myElement);
var myElement = document.querySelectorAll("div");
console.log(myElement);
var myElement = document.getElementById("elzero");
console.log(myElement);
var myElement = document.getElementsByClassName("element");
console.log(myElement);
var myElement = document.getElementsByName("js");
console.log(myElement);
var myElement = document.getElementsByTagName("div");
console.log(myElement);
var myElement = document.body.children[0];
console.log(myElement);
var myElement = document.body.firstElementChild;
console.log(myElement);
var myElement = document.body.childNodes[1];
console.log(myElement);
